import type { Artisan, Product, BulkInquiry, AIActivityMetric, LanguageOption } from '../types';

export const LANGUAGES: LanguageOption[] = [
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', script: 'ગુજરાતી ભાષા પસંદ કરો' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', script: 'अपनी भाषा चुनें' },
  { code: 'en', name: 'English', nativeName: 'English', script: 'Select your language' }
];

export const MOCK_ARTISANS: Artisan[] = [
  {
    id: 'artisan-1',
    name: 'Meena Ben Vankar',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    location: 'Bhuj, Kutch',
    state: 'Gujarat',
    craftType: 'Patola & Handloom Weaving',
    experienceYears: 18,
    story: 'Carrying forward 4 generations of traditional Kutch weaves. Every saree takes up to 3 weeks of painstaking hand-knotting and natural vegetable dyeing.',
    rating: 4.9,
    reviewCount: 38,
    phone: '+91 98250 12345',
    languages: ['gu', 'hi', 'en'],
    isVerified: true,
    publishedCount: 8,
    totalSales: '₹2,45,000'
  },
  {
    id: 'artisan-2',
    name: 'Ram Prasad Kumhar',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    location: 'Jaipur',
    state: 'Rajasthan',
    craftType: 'Traditional Blue Pottery',
    experienceYears: 22,
    story: 'Master craftsman in authentic quartz-based Jaipur Blue Pottery. Decorated with Persian floral motifs passed down through family apprenticeship.',
    rating: 4.8,
    reviewCount: 45,
    phone: '+91 94140 67890',
    languages: ['hi', 'en'],
    isVerified: true,
    publishedCount: 12,
    totalSales: '₹3,80,000'
  },
  {
    id: 'artisan-3',
    name: 'Saraswati Devi',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    location: 'Madhubani',
    state: 'Bihar',
    craftType: 'Mithila / Madhubani Folk Art',
    experienceYears: 15,
    story: 'Paints traditional folklore scenes using natural twig brushes and vegetable dyes on eco-friendly handmade paper and tussar silk.',
    rating: 5.0,
    reviewCount: 29,
    phone: '+91 99340 54321',
    languages: ['hi', 'en'],
    isVerified: true,
    publishedCount: 6,
    totalSales: '₹1,90,000'
  },
  {
    id: 'artisan-4',
    name: 'Ganesh Acharya',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    location: 'Channapatna',
    state: 'Karnataka',
    craftType: 'Lacquered Wooden Craft',
    experienceYears: 12,
    story: 'Specialist in non-toxic organic lacquer wooden toys and home accents crafted from sustainable Wrightia tinctoria wood.',
    rating: 4.7,
    reviewCount: 52,
    phone: '+91 98450 98765',
    languages: ['en', 'hi'],
    isVerified: true,
    publishedCount: 15,
    totalSales: '₹4,12,000'
  },
  {
    id: 'artisan-5',
    name: 'Sunita & Devji Kutchhi',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    location: 'Anjar, Kutch',
    state: 'Gujarat',
    craftType: 'Mirror Work & Rabari Embroidery',
    experienceYears: 20,
    story: 'Preserving intricate Rabari mirror embroidery wall hangings and dupattas, celebrating tribal motifs and Vibrant Kutchi heritage.',
    rating: 4.9,
    reviewCount: 64,
    phone: '+91 97230 45678',
    languages: ['gu', 'hi'],
    isVerified: true,
    publishedCount: 10,
    totalSales: '₹3,15,000'
  }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Handwoven Kutch Single Ikat Cotton Saree',
    titleGujarati: 'હાથથી વણેલી કચ્છી સિંગલ ઇકત કોટન સાડી',
    titleHindi: 'हथकरघा कच्छ सिंगल इकत सूती साड़ी',
    artisanId: 'artisan-1',
    artisanName: 'Meena Ben Vankar',
    artisanAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    artisanLocation: 'Bhuj, Gujarat',
    category: 'Textiles',
    material: 'Pure Organic Cotton & Organic Indigo Dye',
    craftType: 'Single Ikat Weaving',
    origin: 'Kutch, Gujarat',
    price: 2499,
    originalImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
    enhancedImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
    descriptionEn: 'Exquisite handwoven cotton saree crafted by artisan Meena Ben using natural indigo vegetable dyes. Lightweight, breathable, featuring traditional geometric Ikat border details.',
    descriptionHi: 'कारीगर मीना बेन द्वारा प्राकृतिक नील के रंगों से तैयार की गई सुंदर सूती साड़ी। हल्की, आरामदायक और पारंपरिक इकत डिज़ाइन वाली।',
    descriptionGu: 'કારીગર મીના બેન દ્વારા ઓર્ગેનિક ઇન્ડિગો કલરથી બનેલી સુંદર કોટન સાડી. સુતરાઉ અને ટકાઉ ઇકત બોર્ડર સાથે.',
    isAiEnhanced: true,
    status: 'Published',
    views: 420,
    inquiriesCount: 12,
    stock: 5,
    productionCost: 1350,
    recommendedPrice: 2499,
    marketRange: { min: 2200, max: 2800 },
    pricingConfidence: 89,
    createdAt: '2026-08-15'
  },
  {
    id: 'prod-2',
    title: 'Hand-painted Royal Persian Blue Pottery Vase',
    titleGujarati: 'હાથથી દોરેલ જાડી પર્શિયન બ્લુ પોટરી વાઝ',
    titleHindi: 'हस्तनिर्मित जापानी पर्सियन ब्लू पॉटरी फूलदान',
    artisanId: 'artisan-2',
    artisanName: 'Ram Prasad Kumhar',
    artisanAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    artisanLocation: 'Jaipur, Rajasthan',
    category: 'Pottery',
    material: 'Quartz Powder & Egyptian Paste Glass',
    craftType: 'Jaipur Blue Pottery',
    origin: 'Jaipur, Rajasthan',
    price: 1850,
    originalImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=800',
    enhancedImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=800',
    descriptionEn: 'Authentic 10-inch Jaipur Blue Pottery flower vase with cobalt blue oxide motifs. Crafted without clay using traditional quartz paste technique.',
    descriptionHi: 'कोबाल्ट नीले रंगों से सजा 10-इंच जयपुर ब्लू पॉटरी फूलदान। बिना मिट्टी के क्वार्ट्ज़ पेस्ट से निर्मित।',
    descriptionGu: '10 ઇંચનો અધિકૃત જયપુર બ્લુ પોટરી ફ્લાવર વાઝ. કોઈ માટી વગર ગ્લાસ ક્વોર્ટઝ પાવડરથી બનાવેલ.',
    isAiEnhanced: true,
    status: 'Published',
    views: 310,
    inquiriesCount: 8,
    stock: 8,
    productionCost: 950,
    recommendedPrice: 1850,
    marketRange: { min: 1600, max: 2100 },
    pricingConfidence: 91,
    createdAt: '2026-08-18'
  },
  {
    id: 'prod-3',
    title: 'Madhubani Tree of Life Folk Art Canvas',
    titleGujarati: 'મધુબની ટ્રી ઓફ લાઈફ ફોક આર્ટ કેનવાસ',
    titleHindi: 'मधुबनी ट्री ऑफ लाइफ लोक कला पेंटिंग',
    artisanId: 'artisan-3',
    artisanName: 'Saraswati Devi',
    artisanAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    artisanLocation: 'Madhubani, Bihar',
    category: 'Art',
    material: 'Handmade Tussar Silk Paper & Natural Dyes',
    craftType: 'Mithila / Madhubani Painting',
    origin: 'Madhubani, Bihar',
    price: 3200,
    originalImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=800',
    enhancedImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=800',
    descriptionEn: 'Original Tree of Life Madhubani painting painted with bamboo nibs and natural plant colors. Symbolizes growth, harmony, and prosperity.',
    descriptionHi: 'प्राकृतिक रंगों और बांस की कलम से चित्रित मूल मधुबनी पेंटिंग। समृद्धि और प्रकृति का सुंदर प्रतीक।',
    descriptionGu: 'કુદરતી રંગો અને વાંસની કલમથી ચિત્રિત મધુબની આર્ટ. ઘરમાં સમૃદ્ધિ અને સુંદરતા લાવે છે.',
    isAiEnhanced: true,
    status: 'Published',
    views: 580,
    inquiriesCount: 19,
    stock: 3,
    productionCost: 1400,
    recommendedPrice: 3200,
    marketRange: { min: 2900, max: 3600 },
    pricingConfidence: 85,
    createdAt: '2026-08-20'
  },
  {
    id: 'prod-4',
    title: 'Channapatna Organic Wooden Stacking Toy Set',
    titleGujarati: 'ચન્નાપટના ઓર્ગેનિક લાકડાનું રમકડું',
    titleHindi: 'चन्नापटना आर्गेनिक लकड़ी का खिलौना सेट',
    artisanId: 'artisan-4',
    artisanName: 'Ganesh Acharya',
    artisanAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    artisanLocation: 'Channapatna, Karnataka',
    category: 'Woodcraft',
    material: 'Ivory Wood (Wrightia tinctoria) & Vegetable Lacquer',
    craftType: 'Channapatna Toy Craft',
    origin: 'Channapatna, Karnataka',
    price: 890,
    originalImage: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=800',
    enhancedImage: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=800',
    descriptionEn: 'Child-safe non-toxic wooden educational stacking ring toy. Colored with natural turmeric and indigo lac dyes.',
    descriptionHi: 'बच्चों के लिए सुरक्षित प्राकृतिक रंगों से रंगा लकड़ी का खिलौना।',
    descriptionGu: 'બાળકો માટે ૧૦૦% સુરક્ષિત અને હળદર-ઇન્ડિગો રંગથી બનાવેલું લાકડાનું રમકડું.',
    isAiEnhanced: true,
    status: 'Published',
    views: 290,
    inquiriesCount: 15,
    stock: 25,
    productionCost: 420,
    recommendedPrice: 890,
    marketRange: { min: 800, max: 1000 },
    pricingConfidence: 94,
    createdAt: '2026-08-22'
  },
  {
    id: 'prod-5',
    title: 'Rabari Hand-embroidered Mirror Work Tapestry',
    titleGujarati: 'રબારી આભલા ભરતકામ વોલ હેંગિંગ',
    titleHindi: 'रबारी हाथ-कढ़ाई शीशा वर्क वॉल हैगिंग',
    artisanId: 'artisan-5',
    artisanName: 'Sunita & Devji Kutchhi',
    artisanAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    artisanLocation: 'Anjar, Gujarat',
    category: 'Home Decor',
    material: 'Handloom Cotton, Glass Mirrors, Silk Thread',
    craftType: 'Kutch Embroidery',
    origin: 'Kutch, Gujarat',
    price: 3850,
    originalImage: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&q=80&w=800',
    enhancedImage: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&q=80&w=800',
    descriptionEn: 'Vibrant wall tapestry handcrafted with authentic Rabari mirror stitch work and tassel details. Represents Kutchi desert celebration traditions.',
    descriptionHi: 'असली रबारी कढ़ाई और शीशों से सजा पारंपरिक वॉल हैंगिंग।',
    descriptionGu: 'અસલી રબારી આભલા ભરતકામ અને કચ્છી તોરણ વાળી વોલ હેંગિંગ.',
    isAiEnhanced: true,
    status: 'Published',
    views: 610,
    inquiriesCount: 22,
    stock: 4,
    productionCost: 1900,
    recommendedPrice: 3850,
    marketRange: { min: 3500, max: 4200 },
    pricingConfidence: 87,
    createdAt: '2026-08-24'
  }
];

export const MOCK_INQUIRIES: BulkInquiry[] = [
  {
    id: 'inq-101',
    productId: 'prod-1',
    productTitle: 'Handwoven Kutch Single Ikat Cotton Saree',
    productImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
    buyerName: 'Anita Sharma',
    buyerCompany: 'Heritage Craft Boutique Mumbai',
    buyerPhone: '+91 98200 11223',
    buyerEmail: 'anita@heritageboutique.in',
    artisanId: 'artisan-1',
    artisanName: 'Meena Ben Vankar',
    quantity: 50,
    targetPrice: 2150,
    message: 'Namaste Meena Ben! We love your Ikat weave sarees. We are interested in placing a bulk order of 50 units for our upcoming Diwali exhibition. Could you provide estimated delivery timeline?',
    deliveryLocation: 'Bandra West, Mumbai, Maharashtra',
    status: 'NEW',
    createdAt: '2026-08-29'
  },
  {
    id: 'inq-102',
    productId: 'prod-2',
    productTitle: 'Hand-painted Royal Persian Blue Pottery Vase',
    productImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=800',
    buyerName: 'Rahul Mehta',
    buyerCompany: 'Jaipur Living Home Decor Stores',
    buyerPhone: '+91 98111 44556',
    buyerEmail: 'rahul@jaipurliving.com',
    artisanId: 'artisan-2',
    artisanName: 'Ram Prasad Kumhar',
    quantity: 100,
    targetPrice: 1600,
    message: 'We are expanding our luxury homeware line across 4 retail stores. Looking for 100 blue pottery vases. Can we negotiate on price for guaranteed monthly orders?',
    deliveryLocation: 'Gurugram, Haryana',
    status: 'ACCEPTED',
    createdAt: '2026-08-27'
  },
  {
    id: 'inq-103',
    productId: 'prod-4',
    productTitle: 'Channapatna Organic Wooden Stacking Toy Set',
    productImage: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=800',
    buyerName: 'Kavita Roy',
    buyerCompany: 'Little Explorers Preschool Chain',
    buyerPhone: '+91 97400 88990',
    buyerEmail: 'kavita@littleexplorers.edu.in',
    artisanId: 'artisan-4',
    artisanName: 'Ganesh Acharya',
    quantity: 200,
    targetPrice: 750,
    message: 'We want eco-friendly non-toxic wooden toys for our 12 schools in Bengaluru. Would love to confirm custom color combinations.',
    deliveryLocation: 'Indiranagar, Bengaluru',
    status: 'COUNTERED',
    counterPrice: 810,
    createdAt: '2026-08-28'
  }
];

export const MOCK_AI_METRICS: AIActivityMetric[] = [
  { id: 'metric-1', type: 'IMAGE_ENHANCE', artisanName: 'Meena Ben Vankar', status: 'SUCCESS', durationMs: 1420, timestamp: '10 mins ago' },
  { id: 'metric-2', type: 'SPEECH_CATALOGUE', artisanName: 'Ram Prasad Kumhar', status: 'SUCCESS', durationMs: 2100, timestamp: '25 mins ago' },
  { id: 'metric-3', type: 'PRICING_ENGINE', artisanName: 'Saraswati Devi', status: 'SUCCESS', durationMs: 850, timestamp: '1 hour ago' },
  { id: 'metric-4', type: 'TRANSLATION', artisanName: 'Ganesh Acharya', status: 'SUCCESS', durationMs: 620, timestamp: '2 hours ago' },
  { id: 'metric-5', type: 'IMAGE_ENHANCE', artisanName: 'Sunita Kutchhi', status: 'SUCCESS', durationMs: 1890, timestamp: '3 hours ago' }
];
