import type { Artisan, Product, BulkInquiry, AIActivityMetric, LanguageOption } from '../types';

export const LANGUAGES: LanguageOption[] = [
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', script: 'ગુજરાતી ભાષા પસંદ કરો' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', script: 'अपनी भाषा चुनें' },
  { code: 'en', name: 'English', nativeName: 'English', script: 'Select your language' }
];

export const MOCK_ARTISANS: Artisan[] = [
  {
    id: 'artisan-1',
    name: 'Meena Ben Vankar',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    location: 'Bhuj, Kutch',
    state: 'Gujarat',
    craftType: 'Handloom & Patola Weaving',
    experienceYears: 18,
    story: 'Carrying forward 4 generations of traditional Kutch handloom weaving. Specialized in organic cotton and natural plant dyeing.',
    rating: 4.9,
    reviewCount: 38,
    phone: '+91 98250 12345',
    languages: ['gu', 'hi', 'en'],
    isVerified: true,
    publishedCount: 6,
    totalSales: '₹1,85,000'
  },
  {
    id: 'artisan-2',
    name: 'Ramesh Prajapati',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    location: 'Jaipur',
    state: 'Rajasthan',
    craftType: 'Terracotta Pottery & Blue Pottery',
    experienceYears: 22,
    story: 'Master potter crafting handmade terracotta water cooling pots and traditional royal Jaipur blue pottery ceramic tablewares.',
    rating: 4.8,
    reviewCount: 52,
    phone: '+91 98290 54321',
    languages: ['hi', 'en'],
    isVerified: true,
    publishedCount: 8,
    totalSales: '₹2,40,000'
  },
  {
    id: 'artisan-3',
    name: 'Sunita Devi',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    location: 'Madhubani',
    state: 'Bihar',
    craftType: 'Mithila / Madhubani Painting',
    experienceYears: 15,
    story: 'Indigenous Mithila artist painting vibrant natural pigment folk stories on handmade recycled cotton paper and silk fabrics.',
    rating: 5.0,
    reviewCount: 29,
    phone: '+91 94310 98765',
    languages: ['hi', 'en'],
    isVerified: true,
    publishedCount: 5,
    totalSales: '₹1,20,000'
  }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Kutch Handwoven Single Ikat Cotton Saree',
    titleGujarati: 'કચ્છી હાથથી વણેલી સિંગલ ઇકત કોટન સાડી',
    titleHindi: 'कच्छ हथकरघा सिंगल इकत सूती साड़ी',
    artisanId: 'artisan-1',
    artisanName: 'Meena Ben Vankar',
    artisanAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    artisanLocation: 'Bhuj, Kutch, Gujarat',
    category: 'Textiles',
    material: 'Pure Organic Cotton & Indigo Natural Dye',
    craftType: 'Patola & Handloom Weaving',
    origin: 'Kutch, Gujarat',
    price: 2499,
    originalImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
    enhancedImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
    descriptionEn: 'Authentic handwoven Kutch single Ikat saree crafted using 100% organic cotton yarn and natural indigo vat dyes. Soft, breathable texture suitable for all seasons.',
    descriptionGu: '૧૦૦% ઓર્ગેનિક કોટન અને કુદરતી ગળીના રંગથી બનેલી અસલી કચ્છી ઇકત સાડી. અત્યંત સુંવાળી અને દરેક ઋતુ માટે અનુકૂળ.',
    descriptionHi: '100% आर्गेनिक सूती धागे और प्राकृतिक नील से तैयार प्रामाणिक कच्छ इकत साड़ी। आरामदायक और सुरुचिपूर्ण।',
    isAiEnhanced: true,
    status: 'Published',
    views: 428,
    inquiriesCount: 14,
    stock: 12,
    productionCost: 1400,
    recommendedPrice: 2499,
    marketRange: { min: 2200, max: 3100 },
    pricingConfidence: 94,
    createdAt: '2026-08-28T10:00:00.000Z'
  },
  {
    id: 'prod-2',
    title: 'Hand-painted Blue Pottery Floral Dinner Plate Set',
    titleGujarati: 'હાથથી ચીતરેલ બ્લુ પોટ્રી ફ્લાવર પ્લેટ સેટ',
    titleHindi: 'हाथ से चित्रित ब्लू पॉटरी डिनर प्लेट सेट',
    artisanId: 'artisan-2',
    artisanName: 'Ramesh Prajapati',
    artisanAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    artisanLocation: 'Jaipur, Rajasthan',
    category: 'Pottery',
    material: 'Quartz Stone Powder & Natural Oxide Glaze',
    craftType: 'Jaipur Royal Blue Pottery',
    origin: 'Jaipur, Rajasthan',
    price: 1850,
    originalImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=800',
    enhancedImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=800',
    descriptionEn: 'Traditional Jaipur blue pottery serving plates handcrafted without clay using quartz powder. Decorated with delicate Persian floral motifs.',
    descriptionGu: 'ક્વાર્ટઝ પાવડર અને કુદરતી રંગોથી બનેલી જયપુરની પ્રખ્યાત બ્લુ પોટ્રી પ્લેટ સેટ.',
    descriptionHi: 'पारंपरिक जयपुर ब्लू पॉटरी सर्विंग प्लेट्स। बिना मिट्टी के क्वार्टज़ पाउडर और प्राकृतिक रंगों से निर्मित।',
    isAiEnhanced: true,
    status: 'Published',
    views: 312,
    inquiriesCount: 9,
    stock: 8,
    productionCost: 950,
    recommendedPrice: 1850,
    marketRange: { min: 1600, max: 2300 },
    pricingConfidence: 91,
    createdAt: '2026-08-29T14:30:00.000Z'
  },
  {
    id: 'prod-3',
    title: 'Madhubani Tree of Life Handmade Paper Wall Art',
    titleGujarati: 'મધુબની ટ્રી ઓફ લાઈફ હસ્તનિર્મિત વોલ આર્ટ',
    titleHindi: 'मधुबनी ट्री ऑफ लाइफ हस्तनिर्मित वॉल आर्ट',
    artisanId: 'artisan-3',
    artisanName: 'Sunita Devi',
    artisanAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    artisanLocation: 'Madhubani, Bihar',
    category: 'Art',
    material: 'Handmade Cotton Paper & Plant Pigments',
    craftType: 'Mithila Folk Art',
    origin: 'Madhubani, Bihar',
    price: 1299,
    originalImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=800',
    enhancedImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=800',
    descriptionEn: 'Vibrant Tree of Life painting painted with bamboo twigs and nib pens using organic turmeric, indigo, and leaf juice pigments.',
    descriptionGu: 'વાંસની સળીઓ અને ઓર્ગેનિક રંગોથી તૈયાર કરેલું ટ્રી ઓફ લાઈફ મધુબની પેઇન્ટિંગ.',
    descriptionHi: 'बांस की सींक और प्राकृतिक वानस्पतिक रंगों से निर्मित पारंपरिक मधुबनी ट्री ऑफ लाइफ पेंटिंग।',
    isAiEnhanced: true,
    status: 'Published',
    views: 580,
    inquiriesCount: 21,
    stock: 15,
    productionCost: 600,
    recommendedPrice: 1299,
    marketRange: { min: 1100, max: 1700 },
    pricingConfidence: 96,
    createdAt: '2026-08-30T09:15:00.000Z'
  },
  {
    id: 'prod-4',
    title: 'Hand-carved Sheesham Wood Decorative Coaster Set',
    titleGujarati: 'હાથથી કોતરેલ શીશમ વુડ કોસ્ટર સેટ',
    titleHindi: 'हाथ से नक्काशीदार शीशम वुड कोस्टर सेट',
    artisanId: 'artisan-2',
    artisanName: 'Ramesh Prajapati',
    artisanAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    artisanLocation: 'Jaipur, Rajasthan',
    category: 'Woodcraft',
    material: 'Sustainable Indian Rosewood (Sheesham)',
    craftType: 'Jodhpur Wood Carving',
    origin: 'Rajasthan',
    price: 799,
    originalImage: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&q=80&w=800',
    enhancedImage: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&q=80&w=800',
    descriptionEn: 'Set of 6 intricate hand-carved rosewood coasters polished with natural beeswax for a rich durable finish.',
    descriptionGu: '૬ નંગ કુદરતી મધપૂડાના મીણથી પોલિશ કરેલા શીશમ વુડ કોસ્ટર.',
    descriptionHi: 'शीशम की लकड़ी से बने 6 नक्काशीदार कोस्टर का सेट।',
    isAiEnhanced: false,
    status: 'Published',
    views: 195,
    inquiriesCount: 5,
    stock: 20,
    productionCost: 350,
    recommendedPrice: 799,
    marketRange: { min: 700, max: 1000 },
    pricingConfidence: 89,
    createdAt: '2026-08-31T11:00:00.000Z'
  }
];

export const MOCK_INQUIRIES: BulkInquiry[] = [
  {
    id: 'inq-101',
    productId: 'prod-1',
    productTitle: 'Kutch Handwoven Single Ikat Cotton Saree',
    productImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
    buyerName: 'Anita Sharma',
    buyerCompany: 'Heritage Craft Boutique',
    buyerPhone: '+91 98200 11223',
    buyerEmail: 'anita@heritagecrafts.in',
    artisanId: 'artisan-1',
    artisanName: 'Meena Ben Vankar',
    quantity: 25,
    targetPrice: 2100,
    message: 'We loved the organic indigo texture. We want to place a bulk order of 25 pieces for our upcoming Mumbai craft exhibition.',
    deliveryLocation: 'Mumbai, Maharashtra',
    status: 'NEW',
    createdAt: '2026-09-01T15:00:00.000Z'
  }
];

export const MOCK_AI_METRICS: AIActivityMetric[] = [
  {
    id: 'metric-1',
    type: 'SPEECH_CATALOGUE',
    artisanName: 'Meena Ben Vankar',
    status: 'SUCCESS',
    durationMs: 1420,
    timestamp: '10m ago'
  },
  {
    id: 'metric-2',
    type: 'IMAGE_ENHANCE',
    artisanName: 'Ramesh Prajapati',
    status: 'SUCCESS',
    durationMs: 2150,
    timestamp: '25m ago'
  },
  {
    id: 'metric-3',
    type: 'PRICING_ENGINE',
    artisanName: 'Sunita Devi',
    status: 'SUCCESS',
    durationMs: 890,
    timestamp: '1h ago'
  }
];
